# **Part 1**

### Load Datasheet

In [ ]:
import pandas as pd
import numpy as np
df = pd.read_csv("Sample Files/california_housing_train.csv")


### Data Summary

In [ ]:
df.head(5)

In [ ]:
df.tail(10)

In [ ]:
df.describe()

In [ ]:
print(df['total_bedrooms'].unique(),)
print("Total distinct values = ", df['total_bedrooms'].nunique())

### Data Transformation

In [ ]:
df['bedrooms per total rooms'] = df['total_bedrooms'] / df['total_rooms']
df.head()

In [ ]:
print("Standard deviation = " , df['bedrooms per total rooms'].std(axis= 0))

In [ ]:
print("Mean = " , df['bedrooms per total rooms'].mean(axis= 0))

### Data Filtering

In [ ]:
df_filtered = df[df['median_income'] > 5]
df_filtered.index

In [ ]:
newdf = df[(df['total_rooms'] > 10000.0)  & (df['median_house_value'] < 150000.0) ]
newdf

### Export Modified Data

In [ ]:
#unclear which dataframe is asked here
df.to_csv('part1.csv') #The datframe with just added column
newdf.to_csv('part1final.csv') #Final dataframe

# **Part 2**

### Array Creation and Indexing

In [ ]:
arr1 = np.array(range(1,21))
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [68]:
print(arr1[1::2])

[ 2  4  6  8 10 12 14 16 18 20]


In [70]:
arr2 = np.random.randint(10,101, size = (5,4))
arr2

array([[26, 46, 59, 92],
       [64, 32, 53, 31],
       [22, 50, 87, 61],
       [88, 22, 39, 23],
       [11, 10, 39, 18]], dtype=int32)

In [72]:
mini_arr2 = arr2[0:3,0:2]
mini_arr2

array([[26, 46],
       [64, 32],
       [22, 50]], dtype=int32)

### Array Manipulation

In [73]:
arr1.reshape(4,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [74]:
arr1.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [80]:
# Matrix Multiplication
arr3 = np.random.randint(10, size=(2,3))
arr3

array([[8, 2, 5],
       [3, 2, 7]], dtype=int32)

In [81]:
np.matmul(mini_arr2, arr3)


array([[346, 144, 452],
       [608, 192, 544],
       [326, 144, 460]], dtype=int32)

### Boolean and Fancy Indexing

In [84]:
arr4 = np.random.randint(1,100, size = (50))
arr4

array([63, 48, 89, 24, 91, 64, 78, 89, 69, 22, 97, 32, 29, 55, 57, 39, 81,
       69, 13, 56, 25, 49, 18, 65, 38,  9, 11, 68, 12, 48, 99, 52, 77, 36,
       85, 47, 98, 25, 13, 30, 90, 50, 78, 78, 34, 88, 84, 10, 49, 36],
      dtype=int32)

In [93]:
arr4_extract = arr4[arr4[:] > 50]
print(arr4_extract)
#unclear what is meant by use fancy indexing?
indexes = [1,4,12]
print("Fancy indexing - " , arr4_extract[indexes])

[63 89 91 64 78 89 69 97 55 57 81 69 56 65 68 99 52 77 85 98 90 78 78 88
 84]
Fancy indexing -  [89 78 56]


### Statistical Operations

In [95]:
df = pd.DataFrame(arr2)
df

0   1   2   3
0  26  46  59  92
1  64  32  53  31
2  22  50  87  61
3  88  22  39  23
4  11  10  39  18

In [98]:
df.mean(axis = 0)

0    42.2
1    32.0
2    55.4
3    45.0
dtype: float64

In [99]:
df.max(axis = 0)

0    88
1    50
2    87
3    92
dtype: int32

In [100]:
df.sum(axis = 0)

0    211
1    160
2    277
3    225
dtype: int64